---
- name: Criação do container do Nginx
  docker_container:
    name: nginx
    image: nginx
    ports:
      - "80:8080"
    volumes:
      - "/Desktop/Lab_06_Devops/ansible/nginx/files/site.html:/usr/share/nginx/html/site.html"
    state: started